# Config for naming logging directory
run_id: 'evaluation_single_graphs'
add_date: True

# Config for logging directory path
output_path : 'C:\Users\maxil\Documents\projects\master_thesis\nuscenes_tracking_results' 

# Config to load previous model
# load_checkpoint : False # Set to true to load a previous checkpoint
# overwrite_saved_hparam: False # Set to true to if you want to use new hyperparameters(Defined in this config file) 
# ckpt_path: 'experiments/path_/to/_checkpoint.ckpt'
ckpt_path: 'C:\Users\maxil\Documents\projects\master_thesis\spatio-temporal-graph-builer\checkpoints\05-05_18_30_train_w_LR_scheduler\model_checkpoints\epoch=17-step=48329.ckpt'

# Config for modes from the nuscenes split
# train_dataset_mode: "train"
# eval_dataset_mode: "val"
test_dataset_mode: "mini_val"

gpu_settings:
  # device_type: "cpu"
  # Specify which GPUs to use
  # device_id: [1] # Specifically takes the gpu associated with cuda:1 
  torch_device: 'cpu'

# train_params:
#   batch_size: 4
#   num_epochs: 200
#   optimizer:
#     type: Adam
#     args:
#       lr: 0.0001
#       weight_decay: 0.001

#   lr_scheduler:
#     type:
#     args:
#       step_size: 7
#       gamma: 0.5

#   num_workers: 0 # Used for dataloaders
#   save_every_epoch: True # Determines if every a checkpoint will be saved for every epoch
#   save_epoch_start: 1 # If the arg above is set to True, determines the first epoch after which we start saving ckpts
#   tensorboard: True
#   num_save_top_k: 2
#   include_custom_checkpointing : True
#   include_early_stopping : True

dataset_params:
  # Preprocessing ParamsL
  load_valid_sequence_sample_list : False
  # If the above is true then specify the path to the pickle files
  # Must be absolutepath until now
  # if mode not train or val then sequence_sample_list_train_path will be loaded into Dataset object
  sequence_sample_list_train_path : # '/media/HDD2/students/maximilian/spatio-temporal-gnn/dataset/preprocess_dataset_mini_nuscenes/sequence_sample_list_mini_train.pkl'
  sequence_sample_list_val_path : #'/media/HDD2/students/maximilian/spatio-temporal-gnn/dataset/preprocess_dataset_mini_nuscenes/sequence_sample_list_mini_val.pkl'

  # Dataset Processing params:
  dataset_version: 'v1.0-mini'
  dataroot : 'C:\Users\maxil\Documents\projects\master_thesis\mini_nuscenes'
  is_windows_path : False

  # Filter Parameter
  # Contains a list of nuscenes class labels.
  # Only detections from these clases will be loaded for the graph
  # filterBoxes_categoryQuery: ['vehicle.car'] 
  filterBoxes_categoryQuery: ['vehicle.car'] 

  # Graph Construction Parameters
  graph_construction_params:
    spatial_knn_num_neighbors: 4
    temporal_knn_num_neighbors : 4
    spatial_shift_timeframes : 20
    max_temporal_edge_length : 2
    
  max_frame_dist: 3 # Maximum number of frames contained in each graph sampled graph
  # Node Features
  node_feature_mode : "centers_and_time" # determines the included node features 
  # Edge Features
  edge_feature_mode : "edge_type" # determines the included edge features 
  # Edge_Label Type
  label_type: "binary" # "binary" or "multiclass"
  # Choose how Graph construction should be handled
  adapt_knn_param: True # if number of objects is below the KNN-Param then K

  # Data Augmentation Params
  augment: False # Determines whether data augmentation is performed

  

data_splits: # See nuscenes.datasplit()
  # train: #['scene-0061', 'scene-0553', 'scene-0655', 'scene-0757', 'scene-0796', 'scene-1077', 'scene-1094', 'scene-1100']
  # val: #['scene-0103', 'scene-0916']
  # test: #[]

eval_params:
  # Logging / Metrics reporting params
  tensorboard: False
  debbuging_mode : True
  visualize_graph : True
  save_graphs : False # only useful if want to visualize built graphs later on
  save_single_graph_submission: False # Only serves to test the json-saving pipeline
  use_gt: True
  tracking_threshold: 0
  # check_val_every_n_epoch: 9999
