# Config for naming logging directory
run_id: 'evaluation'
add_date: True

# Config for logging directory path
output_path : '/media/HDD2/students/maximilian/spatio-temporal-gnn' 

# Config to load previous model
# load_checkpoint : False # Set to true to load a previous checkpoint
# overwrite_saved_hparam: False # Set to true to if you want to use new hyperparameters(Defined in this config file) 
# ckpt_path: 'experiments/path_/to/_checkpoint.ckpt'
ckpt_path: 'experiments/05-05_18:30_train_w_LR_scheduler/model_checkpoints/epoch=17-step=48329.ckpt'

# Config for modes from the nuscenes split
# train_dataset_mode: "train"
# eval_dataset_mode: "val"
test_dataset_mode: "train"

gpu_settings:
  device_type: "gpu"
  # Specify which GPUs to use
  device_id: [1] # Specifically takes the gpu associated with cuda:1 
  torch_device: 'cuda:1'

dataset_params:
  # Preprocessing ParamsL
  load_valid_sequence_sample_list : False
  # If the above is true then specify the path to the pickle files
  # Must be absolutepath until now
  # if mode not train or val then sequence_sample_list_train_path will be loaded into Dataset object
  sequence_sample_list_train_path : #'/media/HDD2/students/maximilian/spatio-temporal-gnn/dataset/preprocess_dataset_nuscenes/sequence_sample_list_train.pkl' 
  sequence_sample_list_val_path : #'/media/HDD2/students/maximilian/spatio-temporal-gnn/dataset/preprocess_dataset_nuscenes/sequence_sample_list_val.pkl'

  # Dataset Processing params:
  dataset_version: 'v1.0-trainval'
  dataroot : '/media/HDD2/Datasets/nuscenes2'
  is_windows_path : False

  # Filter Parameter
  # Contains a list of nuscenes class labels.
  # Only detections from these clases will be loaded for the graph
  filterBoxes_categoryQuery: ['vehicle.car', 'vehicle.bicycle','vehicle.bus', 'vehicle.motorcycle','human.pedestrian', 'vehicle.trailer', 'vehicle.truck'] #['vehicle.car', 'vehicle.bicycle','vehicle.bus', 'vehicle.motorcycle','human.pedestrian', 'vehicle.trailer', 'vehicle.truck']

  # Graph Construction Parameters
  graph_construction_params:
    spatial_knn_num_neighbors: 4
    temporal_knn_num_neighbors : 4
    spatial_shift_timeframes : 20
    max_temporal_edge_length : 2
    
  max_frame_dist: 6 # Maximum number of frames contained in each graph sampled graph
  # Node Features
  node_feature_mode : "centers_and_time" # determines the included node features 
  # Edge Features
  edge_feature_mode : "edge_type" # determines the included edge features 
  # Edge_Label Type
  label_type: "binary" # "binary" or "multiclass"
  # Choose how Graph construction should be handled
  adapt_knn_param: True # if number of objects is below the KNN-Param then K

  # Data Augmentation Params
  augment: False # Determines whether data augmentation is performed


  

data_splits: # See nuscenes.datasplit()
  # train: ['scene-0061', 'scene-0553', 'scene-0655', 'scene-0757', 'scene-0796', 'scene-1077', 'scene-1094', 'scene-1100']
  # val: ['scene-0103', 'scene-0916']
  # test: []

eval_params:
  # Logging / Metrics reporting params
  tensorboard: True
  save_submission: True
  use_gt: True
  tracking_threshold: 0.5
  