# Config for naming logging directory
run_id: 'preprocess_dataset_nuscenes'
add_date: False
cross_val_split: 
# Config for logging directory path
output_path : '/media/HDD2/students/maximilian/spatio-temporal-gnn/' 

# Config for modes from the nuscenes split
train_dataset_mode: "train"
eval_dataset_mode: "val"

gpu_settings:
  torch_device: 'cpu'

dataset_params:
  # Dataset Processing params:
  dataset_version: 'v1.0-trainval'
  dataroot : '/mount/HDD2/Datasets/nuscenes2'
  is_windows_path : False
  # Edge_Label Type
  label_type: "binary" # "binary" or "multiclass"

  # Filter Parameter
  # Contains a list of nuscenes class labels.
  # Only detections from these clases will be loaded for the graph
  # filterBoxes_categoryQuery: ['vehicle.car'] 
  filterBoxes_categoryQuery: ['vehicle.car'] 

  # Data Augmentation Params
  augment: False # Determines whether data augmentation is performed

  # Graph Construction Parameters
  max_frame_dist: 3 # Maximum number of frames contained in each graph sampled graph
  node_feature_mode : "centers_and_time" # determines the included node features 
  edge_feature_mode : "edge_type" # determines the included edge features 

  # Choose how Graph construction should be handled
  adapt_knn_param: False # if number of objects is below the KNN-Param then K

data_splits: # See nuscenes.datasplit()
  train: ['scene-0061', 'scene-0553', 'scene-0655', 'scene-0757', 'scene-0796', 'scene-1077', 'scene-1094', 'scene-1100']
  val: ['scene-0103', 'scene-0916']
  test: []

